# Use the official Golang image to create a build artifact.
# This is the build stage.
FROM golang:1.23-bullseye AS builder


# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download


# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Build the Go app
ENV CGO_ENABLED=1
# ENV CC="zig cc -target arm-linux-musleabihf"
# ENV CXX="zig cc -target arm-linux-musleabihf"
# ENV GOARCH=arm
# ENV GOOS=linux 
# ENV OK=-ldflags '-extldflags "-ldl -lc -static"' 
RUN go build -ldflags '-extldflags "-ldl -lc -static"' -o main main.go



# Start a new stage from scratch
FROM alpine:latest

# RUN apk add --no-cache libc6-compat libgcc

# Set the Current Working Directory inside the container
WORKDIR /root/

# Copy the Pre-built binary file from the previous stage
COPY --from=builder /app/main ./
COPY --from=builder /app/.env ./

# Command to run the executable
CMD ["./main"]
